variable PUBLIC_ROUTE_TABLE_A {}
variable PUBLIC_ROUTE_TABLE_B {}
variable PUBLIC_ROUTE_TABLE_C {}
variable PRIVATE_ROUTE_TABLE_A {}
variable PRIVATE_ROUTE_TABLE_B {}
variable PRIVATE_ROUTE_TABLE_C {}
variable S3_ENDPOINT_ID {}
