// GLOBAL VARIABLES
variable REGION {}

// ROUTE TABLE VARIABLES
variable PUBLIC_ROUTE_TABLE_A {}
variable PUBLIC_ROUTE_TABLE_B {}
variable PUBLIC_ROUTE_TABLE_C {}
variable PRIVATE_ROUTE_TABLE_A {}
variable PRIVATE_ROUTE_TABLE_B {}
variable PRIVATE_ROUTE_TABLE_C {}

// ENDPOINT VARIABLES
variable S3_ENDPOINT_ID {}
variable DYNAMODB_ENDPOINT_ID {}
